name: Java CI â€“ Build, Test, SonarCloud, Checkmarx One

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:

  # -------------------
  # 1. BUILD + UNIT TESTS
  # -------------------
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: "25"
          distribution: "temurin"

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B clean package

      - name: Run JUnit tests
        run: mvn test

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: target/surefire-reports/

  # -----------------------
  # 2. SONARCLOUD SCAN
  # -----------------------
  sonarcloud:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "25"
          distribution: "temurin"

      - name: Cache Sonar
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: sonar-${{ runner.os }}

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.java.binaries=./target

  # -----------------------
  # 3. CHECKMARX ONE SAST
  # -----------------------
#   checkmarx-one:
#     needs: build-test
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Run Checkmarx One Scan (SAST)
#         uses: Checkmarx/ast-github-action@v2
#         with:
#           tenant: ${{ secrets.CX_TENANT }}
#           base-url: ${{ secrets.CX_BASE_URI }}
#           api-key: ${{ secrets.CX_APIKEY }}
#           project-name: "java-maven-demo"
#           scan-types: "sast"
#           branch: ${{ github.ref_name }}

#       - name: Upload Checkmarx Report
#         uses: actions/upload-artifact@v4
#         with:
#           name: checkmarx-report
#           path: cx_result.json
